### ISSUE TITLE
During cellnav lost the edit mode

### ISSUE THREAD

**Issue by giuseppe-santoro** [angular-ui/ng-grid#2813]
Assuming that whe are using `ui-grid-edit` and `ui-grid-cellNav` in the grid.
You can try here http://plnkr.co/edit/0YUKlkzP8qlsJCB7gjVN?p=preview

Steps:
- I click on a cell, it goes in editMode and get the focus (**correc**t)
- I press the key "return", the previous cell lost focus & editMode and new cell (down) get  focus & editMode (**correct**)
- I go on by pressing key "return" until reaching the last visible row (**completely correct**)
- I press the key "return" againg and the new cell get the focus but it doesn't get the editMode (**incorrect?**)

The problem is that when we have a scoll event, the cell with the editMode lost the edit mode https://github.com/angular-ui/ng-grid/blob/master/src/features/edit/js/gridEdit.js#L651.

And when I press "return", the cellNav try to make visible the new cell by scrolling a little bit https://github.com/angular-ui/ng-grid/blob/master/src/features/cellnav/js/cellnav.js#L879

I think that is correct to lost the editMode when the grid is scrolled but if it is scrolled by cellNav, it should not lost the editMode.

**Comment by PaulL1** [comment]
Are you on RC19?  I think this got fixed yesterday on master - could you try unstable?

**Comment by giuseppe-santoro** [comment]
Here http://plnkr.co/edit/0YUKlkzP8qlsJCB7gjVN?p=preview I'm using http://ui-grid.info/release/ui-grid-unstable.js

I think it is the last unstable version.

At the header of the file you can read:

```javascript
/*!
 * ui-grid - v3.0.0-rc.19-735af76 - 2015-02-20
 * Copyright (c) 2015 ; License: MIT 
 */
```

**Comment by PaulL1** [comment]
OK, I think this is also associated with the problem I see in #2898.  I'll look at them both together.

**Comment by PaulL1** [comment]
@swalters: I know you're working in edit and editonFocus, so I presume you're either fixing this or that we don't think it needs to be fixed.

**Comment by c0bra** [comment]
I believe this and #2986 are related/duplicates.

**Comment by swalters** [comment]
This is fixed in latest master.  Please reopen if it's not working your scenario.

**Comment by amrutabarwal** [comment]
I click on a cell, it goes in editMode and get the focus (correct)
I press the key "return", the previous cell lost focus & editMode and new cell (down) get focus & editMode (correct)
I go on by pressing key "return" until reaching the last visible row (completely correct)
I press the key "return" againg and the new cell get the focus but it doesn't get the editMode (incorrect?)

Still exist, in latest version.

**Comment by kolekaramol** [comment]
I click on a cell, it goes in editMode and get the focus (correct)
I press the key "return", the previous cell lost focus & editMode and new cell (down) get focus & editMode (correct)
I go on by pressing key "return" until reaching the last visible row (completely correct)
I press the key "return" againg and the new cell get the focus but it doesn't get the editMode (incorrect?)

Issue still exist, in latest version.

Stil exits in latest version
